server:
  port: 7074
spring:
  application:
    name: AdminApi
  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: amresh
#    password: Amresh1998 
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Amresh1998
    url: jdbc:mysql:///jrtp-ish-db
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

plan:
  module:
    messages:
      save-success: Plan is save with id value
      save-failure: Plan is not save with id value   
      find-By-id-failure: Plan is not found
      update-success: plan update success
      update-failure: plan is not found for updation
      delete-success: Plan is deleted
      delete-failure: plan is not found for deletion
      status-change-success: Plan status is changed
      status-change-failure: plan is not found for status changed      